# Some experiments using "Seismic" data

The data used below for the experiments with decision reducts and bireducts is derived from the original dataset used in a data mining challenge hosted on the Knowledgepit platform https://knowledgepit.ml.

For the summary of the challenge please refer to:

```
Andrzej Janusz, Dominik Ślęzak, Marek Sikora, Łukasz Wróbel:
Predicting Dangerous Seismic Events: AAIA'16 Data Mining Challenge. FedCSIS 2016: 205-211
```

or to the data mining challenge page, where the description, results, as well as, the original data can be found - https://knowledgepit.ml/aaia16-data-mining-challenge.

---

We applied feature extraction and unsupervised discretization (quantile-based) to create a dataset for the experiments below - these operations are not included in the notebook, just the final dataset (cf. ``data`` directory). Please note that we only used the training data from the data mining challenge as our dataset for the experiments, splitting it into train-test subsets. It's important to mention that this approach deviates from best practices in machine learning because a random split of a dataset involving or originating from time-series data may introduce data leaks. However, for the purpose of this notebook, which focuses on demonstrating the utilization of decision reducts and bireducts, we will disregard this fact.

In [ ]:
# Install the required packages below

# !pip install more-itertools==8.14.0
# !pip install numpy==1.25.2
# !pip install pandas==2.1.0
# !pip install scikit-learn==1.3.1
# !pip install scikit-rough==0.2.0
# !pip install snakeviz==2.2.0
# !pip install xgboost==2.0.0

In [ ]:
import functools
import pathlib
from collections import defaultdict

import more_itertools
import numpy as np
import pandas as pd
from sklearn.compose import make_column_transformer
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import accuracy_score, balanced_accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier
from skrough.algorithms.reducts import (
    get_approx_reduct_greedy_heuristic,
    get_approx_reduct_daar_heuristic,
)
from skrough.dataprep import prepare_factorized_array, prepare_factorized_vector
from skrough.disorder_measures import gini_impurity
from skrough.feature_importance import (
    get_feature_importance,
)
from skrough.predict.predict_attrs_ensemble import predict_attrs_ensemble
from skrough.predict.predict_objs_attrs_ensemble import predict_objs_attrs_ensemble
from xgboost import XGBClassifier

rng = np.random.default_rng()

# data preparation

In [2]:
DATA_DIR = pathlib.Path("data")

data = pd.read_csv(DATA_DIR / "seismic_training_data_features_discretized.csv")
target = pd.read_csv(DATA_DIR / "seismic_training_labels.csv", header=None)[0]

# drop main_working_id column
data.drop("main_working_id", axis=1, inplace=True)
column_names = data.columns.to_list()

# encode data and target into the form of integers
data = OrdinalEncoder().fit_transform(data)
target = LabelEncoder().fit_transform(target)

# split into train and test subsets
train, test, train_target, test_target = train_test_split(
    data, target, test_size=0.10, random_state=42
)

# Computation of greedy and DAAR-based reducts

Let's use a greedy approach and a function-based DAAR (Dynamically Adjusted Approximation Reducts) heuristic approach:

```
Andrzej Janusz, Dominik Ślęzak:
Computation of Approximate Reducts with Dynamically Adjusted Approximation Threshold. ISMIS 2015: 19-28
```

In [ ]:
greedy_heuristic_reducts = get_approx_reduct_greedy_heuristic(
    x=train,
    y=train_target,
    disorder_fun=gini_impurity,
    epsilon=0.05,
    candidates_count=100,
    n_reducts=100,
    n_jobs=-1,
)

In [ ]:
greedy_heuristic_reducts

[AttrsSubset(attrs=[201, 167, 15, 8, 313, 294, 516, 207, 6, 338, 601, 494, 493, 603, 75, 5, 538]),
 AttrsSubset(attrs=[125, 0, 6, 203, 4, 605, 400, 334, 471, 316, 123, 517, 493, 54, 312, 190, 121]),
 AttrsSubset(attrs=[3, 8, 653, 15, 123, 142, 407, 6, 516, 489, 334, 490, 5, 54, 341, 317, 185]),
 AttrsSubset(attrs=[6, 386, 142, 168, 189, 494, 4, 491, 5, 400, 98, 517, 55, 512, 338, 597]),
 AttrsSubset(attrs=[6, 593, 142, 229, 401, 313, 471, 4, 514, 123, 338, 494, 74, 510, 335, 537]),
 AttrsSubset(attrs=[8, 123, 461, 4, 208, 6, 5, 511, 318, 399, 334, 76, 491, 187, 397, 75]),
 AttrsSubset(attrs=[8, 123, 593, 407, 296, 190, 4, 315, 5, 514, 338, 736, 6, 54, 185, 121]),
 AttrsSubset(attrs=[167, 191, 392, 168, 4, 7, 6, 403, 513, 334, 98, 490, 516, 493, 77, 185]),
 AttrsSubset(attrs=[190, 123, 275, 4, 317, 6, 492, 315, 294, 336, 185, 517, 76, 7, 53, 403]),
 AttrsSubset(attrs=[168, 123, 143, 4, 6, 595, 515, 489, 492, 516, 334, 119, 539, 76, 402]),
 AttrsSubset(attrs=[189, 124, 11, 142, 511, 295, 316, 6, 337, 661, 4, 97, 338, 52, 406, 121]),
 AttrsSubset(attrs=[25, 392, 125, 8, 6, 189, 472, 168, 5, 312, 339, 517, 4, 118, 537, 491, 402]),
 AttrsSubset(attrs=[289, 6, 730, 296, 489, 512, 4, 97, 5, 514, 339, 52, 9, 490, 405, 539]),
 AttrsSubset(attrs=[6, 386, 461, 168, 459, 208, 5, 407, 465, 123, 488, 339, 319, 74, 512, 514, 491]),
 AttrsSubset(attrs=[123, 11, 125, 722, 728, 124, 8, 313, 141, 4, 494, 5, 338, 468, 516, 73, 121, 604]),
 AttrsSubset(attrs=[125, 167, 6, 203, 512, 140, 737, 5, 491, 319, 339, 492, 76, 121, 729, 403]),
 AttrsSubset(attrs=[132, 15, 123, 680, 6, 389, 340, 511, 5, 516, 7, 494, 97, 736, 76, 465, 114]),
 AttrsSubset(attrs=[167, 190, 125, 8, 208, 314, 411, 6, 492, 489, 340, 597, 406, 5, 185, 517, 538]),
 AttrsSubset(attrs=[168, 189, 142, 8, 6, 315, 4, 515, 5, 340, 516, 207, 494, 55, 538, 729]),
 AttrsSubset(attrs=[190, 6, 458, 29, 186, 467, 5, 472, 189, 4, 492, 511, 97, 77, 118, 600]),
 AttrsSubset(attrs=[168, 8, 532, 404, 675, 413, 315, 4, 6, 515, 337, 512, 55, 492, 120, 397]),
 AttrsSubset(attrs=[190, 6, 461, 464, 123, 142, 5, 313, 4, 466, 493, 337, 53, 515, 539, 405]),
 AttrsSubset(attrs=[11, 189, 680, 398, 208, 6, 735, 335, 516, 495, 730, 120, 55, 662, 511, 185]),
 AttrsSubset(attrs=[6, 395, 168, 464, 7, 313, 465, 677, 473, 5, 492, 517, 337, 184, 75, 340]),
 AttrsSubset(attrs=[6, 392, 124, 5, 209, 717, 677, 493, 512, 335, 469, 96, 517, 54, 121, 494]),
 AttrsSubset(attrs=[201, 15, 6, 167, 452, 190, 489, 207, 337, 4, 316, 142, 515, 75, 604, 74, 120]),
 AttrsSubset(attrs=[6, 386, 230, 142, 124, 393, 295, 489, 340, 317, 96, 514, 77, 123, 118, 5, 512]),
 AttrsSubset(attrs=[167, 416, 6, 389, 404, 730, 5, 4, 465, 512, 339, 488, 55, 315, 334, 184]),
 AttrsSubset(attrs=[168, 6, 205, 470, 228, 297, 4, 515, 314, 337, 492, 493, 189, 55, 120, 512]),
 AttrsSubset(attrs=[6, 203, 190, 5, 296, 31, 514, 511, 340, 123, 490, 185, 76, 337, 317, 537]),
 AttrsSubset(attrs=[6, 392, 186, 124, 228, 453, 167, 5, 467, 515, 489, 512, 341, 514, 55, 730]),
 AttrsSubset(attrs=[656, 677, 168, 11, 15, 676, 6, 5, 313, 4, 397, 515, 338, 471, 53, 52, 514]),
 AttrsSubset(attrs=[6, 389, 296, 190, 598, 603, 123, 488, 512, 513, 335, 493, 74, 396, 470, 99]),
 AttrsSubset(attrs=[189, 124, 6, 461, 5, 207, 732, 339, 517, 494, 491, 514, 54, 121, 472, 336]),
 AttrsSubset(attrs=[167, 168, 296, 314, 467, 5, 675, 514, 493, 8, 341, 334, 228, 53, 390, 119, 465]),
 AttrsSubset(attrs=[6, 395, 470, 168, 189, 730, 513, 488, 340, 493, 54, 603, 337, 510, 184, 539]),
 AttrsSubset(attrs=[6, 389, 734, 189, 207, 5, 124, 515, 490, 335, 74, 516, 471, 472, 119, 493]),
 AttrsSubset(attrs=[168, 189, 15, 398, 208, 4, 143, 314, 493, 337, 513, 74, 8, 162, 453, 75, 6]),
 AttrsSubset(attrs=[167, 124, 8, 458, 469, 4, 467, 313, 5, 335, 512, 6, 77, 471, 494, 396]),
 AttrsSubset(attrs=[191, 6, 386, 4, 167, 512, 296, 124, 334, 495, 185, 598, 492, 536, 341, 121]),
 AttrsSubset(attrs=[25, 168, 15, 470, 677, 412, 411, 6, 471, 517, 4, 512, 466, 75, 492, 338, 180]),
 AttrsSubset(attrs=[201, 395, 6, 190, 728, 402, 143, 189, 5, 317, 337, 463, 488, 76, 98, 75, 119]),
 AttrsSubset(attrs=[15, 25, 124, 123, 404, 8, 313, 6, 341, 207, 727, 515, 54, 5, 115, 488, 402]),
 AttrsSubset(attrs=[124, 659, 404, 6, 189, 4, 206, 315, 510, 340, 399, 495, 53, 492, 121, 187]),
 AttrsSubset(attrs=[198, 6, 458, 123, 736, 124, 318, 4, 337, 405, 495, 511, 75, 120, 9, 597]),
 AttrsSubset(attrs=[6, 464, 190, 189, 736, 4, 5, 732, 493, 334, 55, 517, 185, 512, 120]),
 AttrsSubset(attrs=[8, 534, 142, 123, 313, 124, 207, 334, 4, 510, 494, 121, 399, 667, 52, 317, 397]),
 AttrsSubset(attrs=[189, 11, 386, 6, 470, 295, 341, 513, 514, 4, 494, 604, 468, 74, 539, 121]),
 AttrsSubset(attrs=[6, 389, 124, 123, 404, 5, 339, 141, 513, 488, 4, 514, 74, 334, 472, 97]),
 AttrsSubset(attrs=[25, 190, 15, 404, 413, 675, 489, 295, 6, 5, 514, 339, 319, 118, 71, 463, 450]),
 AttrsSubset(attrs=[413, 124, 6, 137, 7, 493, 407, 411, 5, 96, 488, 341, 515, 184, 121, 334]),
 AttrsSubset(attrs=[124, 395, 189, 295, 208, 407, 6, 488, 515, 334, 604, 76, 9, 4, 510, 53]),
 AttrsSubset(attrs=[6, 587, 296, 123, 124, 729, 736, 467, 5, 513, 339, 514, 4, 74, 184, 119]),
 AttrsSubset(attrs=[15, 413, 190, 675, 473, 295, 186, 513, 488, 8, 318, 660, 4, 459, 5, 495, 334, 121]),
 AttrsSubset(attrs=[124, 189, 296, 15, 207, 6, 455, 339, 489, 510, 4, 52, 492, 604, 334, 515]),
 AttrsSubset(attrs=[123, 168, 6, 385, 736, 208, 491, 334, 316, 729, 5, 512, 119, 76, 467, 537]),
 AttrsSubset(attrs=[125, 11, 123, 190, 294, 407, 207, 489, 510, 8, 6, 4, 52, 334, 471, 319, 604]),
 AttrsSubset(attrs=[7, 6, 142, 4, 319, 295, 190, 338, 314, 341, 513, 76, 123, 491, 121, 253]),
 AttrsSubset(attrs=[124, 6, 139, 123, 297, 728, 313, 335, 492, 493, 512, 76, 338, 402, 121, 515]),
 AttrsSubset(attrs=[3, 11, 123, 722, 8, 209, 404, 4, 319, 512, 272, 341, 494, 511, 121, 53, 184, 736]),
 AttrsSubset(attrs=[677, 191, 414, 605, 190, 4, 207, 513, 6, 98, 493, 516, 339, 403, 120, 55, 7]),
 AttrsSubset(attrs=[677, 680, 124, 7, 412, 6, 313, 295, 515, 336, 316, 734, 53, 510, 115, 732, 595]),
 AttrsSubset(attrs=[8, 6, 719, 189, 208, 315, 517, 4, 494, 510, 334, 207, 75, 604, 52, 120]),
 AttrsSubset(attrs=[191, 167, 680, 297, 190, 6, 491, 728, 319, 514, 335, 492, 74, 4, 468, 181, 120]),
 AttrsSubset(attrs=[132, 6, 725, 464, 124, 729, 4, 340, 167, 512, 494, 491, 52, 406, 335, 97]),
 AttrsSubset(attrs=[168, 413, 125, 142, 412, 675, 295, 514, 5, 6, 513, 491, 334, 74, 339, 736, 537]),
 AttrsSubset(attrs=[190, 189, 455, 4, 403, 7, 407, 339, 141, 318, 492, 512, 517, 54, 6, 121]),
 AttrsSubset(attrs=[123, 6, 139, 124, 404, 297, 230, 315, 4, 493, 340, 517, 512, 55, 403, 185]),
 AttrsSubset(attrs=[677, 168, 411, 5, 206, 318, 676, 6, 473, 340, 489, 400, 512, 55, 515, 118]),
 AttrsSubset(attrs=[169, 11, 25, 590, 123, 140, 207, 517, 4, 312, 407, 6, 334, 74, 468, 120, 403, 168]),
 AttrsSubset(attrs=[167, 124, 6, 29, 15, 736, 473, 337, 488, 493, 514, 98, 511, 140, 185, 121]),
 AttrsSubset(attrs=[15, 167, 190, 470, 6, 389, 5, 515, 400, 732, 488, 341, 4, 119, 491, 539]),
 AttrsSubset(attrs=[135, 11, 6, 386, 167, 294, 168, 315, 207, 341, 493, 516, 492, 77, 9, 661, 119]),
 AttrsSubset(attrs=[15, 123, 11, 8, 392, 143, 489, 513, 206, 5, 6, 4, 98, 472, 119, 75, 337]),
 AttrsSubset(attrs=[189, 6, 137, 207, 229, 404, 490, 513, 514, 340, 495, 5, 53, 468, 335, 119]),
 AttrsSubset(attrs=[190, 386, 15, 6, 7, 677, 5, 341, 208, 510, 517, 494, 491, 400, 119, 539]),
 AttrsSubset(attrs=[8, 226, 124, 123, 33, 317, 5, 6, 491, 510, 98, 186, 494, 121, 339, 75]),
 AttrsSubset(attrs=[189, 124, 461, 296, 8, 315, 7, 295, 494, 337, 493, 516, 735, 4, 76, 601, 121]),
 AttrsSubset(attrs=[6, 719, 404, 598, 7, 732, 4, 489, 189, 335, 512, 317, 121, 539, 124, 513]),
 AttrsSubset(attrs=[680, 6, 386, 123, 208, 341, 495, 515, 316, 207, 4, 54, 603, 490, 121, 510]),
 AttrsSubset(attrs=[190, 6, 461, 189, 142, 491, 209, 336, 517, 729, 4, 54, 512, 469, 537, 514]),
 AttrsSubset(attrs=[124, 6, 247, 123, 319, 334, 33, 5, 514, 490, 465, 511, 54, 187, 537, 402]),
 AttrsSubset(attrs=[15, 123, 168, 209, 296, 6, 491, 207, 515, 492, 341, 4, 334, 537, 96, 510]),
 AttrsSubset(attrs=[190, 722, 11, 675, 189, 15, 295, 315, 5, 6, 337, 516, 120, 53, 604, 495, 340]),
 AttrsSubset(attrs=[201, 8, 534, 169, 4, 6, 206, 123, 513, 493, 5, 336, 488, 76, 403, 121, 729]),
 AttrsSubset(attrs=[189, 168, 142, 169, 6, 511, 141, 5, 312, 4, 317, 336, 339, 54, 604, 492]),
 AttrsSubset(attrs=[179, 8, 7, 587, 407, 142, 189, 510, 730, 96, 4, 491, 74, 492, 517, 119, 335]),
 AttrsSubset(attrs=[6, 386, 167, 15, 512, 142, 466, 339, 465, 494, 4, 315, 190, 120, 77, 599]),
 AttrsSubset(attrs=[659, 7, 167, 15, 124, 407, 4, 6, 315, 515, 334, 492, 185, 512, 468, 54]),
 AttrsSubset(attrs=[413, 123, 190, 11, 191, 737, 7, 466, 491, 341, 494, 6, 517, 120, 5, 510, 96]),
 AttrsSubset(attrs=[6, 386, 395, 124, 123, 208, 491, 141, 512, 492, 341, 4, 120, 515, 53, 397]),
 AttrsSubset(attrs=[190, 534, 189, 470, 8, 6, 515, 5, 207, 732, 512, 339, 491, 77, 463, 184]),
 AttrsSubset(attrs=[189, 15, 11, 8, 124, 511, 7, 403, 473, 5, 6, 339, 185, 76, 492, 402, 510]),
 AttrsSubset(attrs=[123, 190, 407, 11, 4, 7, 6, 511, 318, 294, 339, 406, 492, 74, 186, 456]),
 AttrsSubset(attrs=[8, 123, 169, 7, 395, 168, 470, 511, 4, 295, 493, 55, 338, 396, 6, 604, 514]),
 AttrsSubset(attrs=[123, 7, 722, 124, 407, 5, 6, 206, 313, 514, 338, 490, 119, 495, 76, 397]),
 AttrsSubset(attrs=[124, 123, 6, 452, 15, 404, 313, 493, 492, 4, 334, 512, 54, 185, 121, 406]),
 AttrsSubset(attrs=[168, 413, 11, 167, 404, 452, 313, 207, 4, 492, 336, 512, 186, 6, 468, 54, 403]),
 AttrsSubset(attrs=[6, 719, 142, 297, 190, 5, 319, 4, 123, 338, 314, 53, 463, 337, 120, 492]),
 AttrsSubset(attrs=[678, 158, 7, 167, 341, 515, 6, 403, 514, 465, 491, 52, 4, 185, 732, 115])]

In [ ]:
daar_heuristic_reducts = get_approx_reduct_daar_heuristic(
    x=train,
    y=train_target,
    disorder_fun=gini_impurity,
    candidates_count=100,
    allowed_randomness=0.05,
    probes_count=100,
    fast=True,
    n_reducts=100,
    n_jobs=-1,
)

In [ ]:
daar_heuristic_reducts

[AttrsSubset(attrs=[123, 124, 6, 291, 296, 488, 5, 493, 339, 4, 514]),
 AttrsSubset(attrs=[0, 8, 650, 395, 404, 124, 511, 411, 604, 4, 399, 492, 338]),
 AttrsSubset(attrs=[8, 189, 534, 7, 6, 729, 208, 515, 492, 491]),
 AttrsSubset(attrs=[8, 652, 0, 11, 167, 6, 736, 250, 731, 513, 340, 4, 318]),
 AttrsSubset(attrs=[168, 8, 6, 452, 470, 207, 5, 732, 515, 123, 510]),
 AttrsSubset(attrs=[15, 412, 189, 190, 8, 4, 488, 7, 313, 143, 340, 463]),
 AttrsSubset(attrs=[123, 8, 659, 7, 124, 464, 15, 511, 726, 6, 406, 5, 4]),
 AttrsSubset(attrs=[680, 6, 725, 404, 4, 295, 335, 252, 319, 412, 488, 5]),
 AttrsSubset(attrs=[6, 533, 470, 190, 412, 597, 296, 515, 490, 5]),
 AttrsSubset(attrs=[123, 458, 125, 8, 124, 470, 315, 4, 207, 514, 515, 732, 337]),
 AttrsSubset(attrs=[0, 15, 458, 11, 8, 677, 294, 5, 7, 737, 603, 319, 513, 339]),
 AttrsSubset(attrs=[286, 168, 8, 458, 189, 6, 274, 318, 5, 466, 465, 488]),
 AttrsSubset(attrs=[189, 8, 7, 395, 295, 208, 407, 600, 318, 513, 337]),
 AttrsSubset(attrs=[6, 461, 407, 190, 728, 4, 736, 5, 167, 335, 492]),
 AttrsSubset(attrs=[6, 719, 297, 189, 124, 339, 5, 493, 492, 516, 511]),
 AttrsSubset(attrs=[168, 6, 29, 732, 123, 470, 511, 207, 492, 317, 334]),
 AttrsSubset(attrs=[15, 168, 167, 473, 142, 413, 488, 4, 8, 511, 5, 465]),
 AttrsSubset(attrs=[123, 8, 15, 392, 208, 190, 6, 511, 5, 317, 339, 185]),
 AttrsSubset(attrs=[6, 461, 734, 168, 123, 207, 488, 489, 4, 515, 340]),
 AttrsSubset(attrs=[124, 8, 6, 461, 734, 189, 730, 315, 729, 316, 334]),
 AttrsSubset(attrs=[190, 8, 650, 142, 7, 593, 4, 489, 189, 6, 341, 510]),
 AttrsSubset(attrs=[124, 722, 123, 8, 404, 489, 5, 31, 6, 516, 339, 515]),
 AttrsSubset(attrs=[6, 458, 168, 271, 228, 208, 189, 494, 407, 4, 515, 339]),
 AttrsSubset(attrs=[189, 8, 6, 719, 470, 598, 513, 317, 516, 5, 124]),
 AttrsSubset(attrs=[189, 6, 722, 470, 124, 295, 469, 4, 315, 339, 516]),
 AttrsSubset(attrs=[168, 169, 167, 404, 8, 295, 489, 4, 7, 511, 334, 6, 98]),
 AttrsSubset(attrs=[0, 8, 189, 15, 512, 5, 295, 513, 732, 6, 340, 488]),
 AttrsSubset(attrs=[25, 169, 167, 190, 404, 294, 735, 141, 335, 4, 604, 317, 6]),
 AttrsSubset(attrs=[289, 11, 189, 169, 168, 6, 389, 404, 339, 317, 490, 207]),
 AttrsSubset(attrs=[190, 123, 169, 470, 488, 402, 335, 207, 338, 511, 8]),
 AttrsSubset(attrs=[15, 124, 677, 189, 11, 470, 143, 140, 317, 340, 488, 8, 4]),
 AttrsSubset(attrs=[168, 8, 653, 167, 470, 6, 5, 512, 489, 207, 334]),
 AttrsSubset(attrs=[124, 189, 11, 169, 209, 208, 99, 337, 489, 5, 6, 318]),
 AttrsSubset(attrs=[289, 125, 189, 8, 11, 6, 395, 398, 209, 512, 491, 317, 339]),
 AttrsSubset(attrs=[123, 168, 6, 722, 734, 297, 317, 337, 510, 492]),
 AttrsSubset(attrs=[6, 719, 142, 190, 7, 167, 5, 511, 495, 295, 514]),
 AttrsSubset(attrs=[189, 8, 395, 294, 4, 6, 735, 340, 312, 5, 493, 168]),
 AttrsSubset(attrs=[135, 550, 11, 392, 189, 8, 4, 469, 143, 318, 513, 335]),
 AttrsSubset(attrs=[6, 395, 464, 407, 168, 317, 488, 5, 189, 727, 512]),
 AttrsSubset(attrs=[15, 168, 656, 296, 735, 123, 6, 319, 312, 489, 4, 5]),
 AttrsSubset(attrs=[8, 123, 6, 593, 297, 168, 5, 731, 313, 492, 339]),
 AttrsSubset(attrs=[167, 124, 11, 470, 125, 461, 314, 489, 295, 336, 8, 515, 4, 6]),
 AttrsSubset(attrs=[167, 124, 11, 8, 15, 6, 719, 473, 334, 488, 206, 319, 4]),
 AttrsSubset(attrs=[168, 15, 29, 296, 6, 312, 167, 207, 319, 511, 98]),
 AttrsSubset(attrs=[168, 413, 15, 6, 392, 675, 676, 318, 493, 206, 334, 511]),
 AttrsSubset(attrs=[190, 8, 15, 412, 407, 587, 167, 9, 4, 517, 6, 334]),
 AttrsSubset(attrs=[124, 6, 389, 167, 142, 4, 295, 315, 339, 494, 510]),
 AttrsSubset(attrs=[201, 680, 125, 189, 8, 470, 7, 491, 6, 4, 334, 406, 515, 516]),
 AttrsSubset(attrs=[8, 167, 6, 389, 733, 473, 466, 468, 513, 5, 168, 335]),
 AttrsSubset(attrs=[0, 168, 11, 461, 6, 297, 99, 398, 495, 253, 338, 123]),
 AttrsSubset(attrs=[680, 167, 470, 11, 190, 125, 675, 8, 9, 313, 4, 514, 495, 5]),
 AttrsSubset(attrs=[11, 167, 190, 125, 719, 143, 404, 4, 511, 488, 31, 336, 99]),
 AttrsSubset(attrs=[190, 395, 8, 15, 208, 405, 123, 5, 313, 339, 494, 515]),
 AttrsSubset(attrs=[123, 549, 15, 416, 8, 473, 4, 313, 5, 294, 334, 318]),
 AttrsSubset(attrs=[167, 191, 190, 296, 6, 203, 489, 207, 339, 493, 492]),
 AttrsSubset(attrs=[15, 135, 722, 6, 208, 190, 603, 5, 407, 334, 315, 510]),
 AttrsSubset(attrs=[168, 189, 404, 125, 140, 4, 8, 6, 337, 493, 512]),
 AttrsSubset(attrs=[190, 8, 593, 6, 296, 729, 338, 488, 407, 516]),
 AttrsSubset(attrs=[189, 141, 351, 168, 6, 386, 315, 296, 317, 334, 492]),
 AttrsSubset(attrs=[15, 201, 680, 123, 8, 6, 736, 725, 208, 272, 492, 5, 337]),
 AttrsSubset(attrs=[124, 167, 6, 455, 296, 494, 493, 141, 513, 4, 5, 337]),
 AttrsSubset(attrs=[123, 351, 11, 392, 15, 190, 470, 4, 511, 209, 494, 334, 140, 319]),
 AttrsSubset(attrs=[6, 587, 404, 124, 4, 733, 167, 511, 295, 335]),
 AttrsSubset(attrs=[311, 190, 142, 189, 169, 585, 6, 315, 5, 4, 336, 318]),
 AttrsSubset(attrs=[124, 123, 8, 296, 395, 511, 209, 314, 4, 514, 340]),
 AttrsSubset(attrs=[168, 8, 534, 189, 142, 7, 6, 494, 334, 317, 5, 207]),
 AttrsSubset(attrs=[190, 725, 6, 142, 189, 730, 494, 4, 334, 515]),
 AttrsSubset(attrs=[6, 587, 167, 168, 296, 512, 4, 319, 295, 5, 339]),
 AttrsSubset(attrs=[124, 6, 395, 123, 403, 470, 251, 207, 339, 468, 513]),
 AttrsSubset(attrs=[3, 123, 11, 534, 207, 190, 7, 4, 313, 208, 8, 514, 334]),
 AttrsSubset(attrs=[169, 722, 190, 8, 229, 404, 189, 494, 6, 336, 313, 339]),
 AttrsSubset(attrs=[190, 15, 8, 650, 7, 412, 737, 677, 6, 515, 489, 462, 512]),
 AttrsSubset(attrs=[15, 123, 722, 168, 8, 6, 5, 315, 142, 471, 339, 512]),
 AttrsSubset(attrs=[0, 11, 125, 123, 6, 386, 208, 5, 517, 492, 489, 340, 510]),
 AttrsSubset(attrs=[6, 719, 404, 189, 15, 168, 295, 511, 491, 4, 317, 338]),
 AttrsSubset(attrs=[25, 6, 139, 392, 297, 142, 124, 4, 340, 517, 494]),
 AttrsSubset(attrs=[8, 6, 389, 190, 468, 123, 334, 297, 316, 315, 4]),
 AttrsSubset(attrs=[198, 15, 8, 6, 719, 168, 208, 341, 5, 189, 514, 465, 315]),
 AttrsSubset(attrs=[8, 224, 676, 190, 11, 733, 413, 313, 6, 4, 515, 473, 338]),
 AttrsSubset(attrs=[132, 722, 8, 190, 404, 123, 9, 6, 319, 512, 340, 471, 4]),
 AttrsSubset(attrs=[25, 15, 189, 297, 678, 124, 495, 6, 313, 4, 397, 341, 516]),
 AttrsSubset(attrs=[123, 11, 6, 736, 389, 142, 317, 124, 5, 492, 337]),
 AttrsSubset(attrs=[168, 11, 392, 677, 15, 407, 140, 675, 490, 8, 6, 334, 317]),
 AttrsSubset(attrs=[413, 676, 168, 6, 404, 313, 294, 493, 4, 510, 336]),
 AttrsSubset(attrs=[190, 191, 6, 389, 398, 468, 167, 4, 317, 406, 512]),
 AttrsSubset(attrs=[25, 11, 8, 123, 6, 722, 336, 729, 208, 494, 5, 491]),
 AttrsSubset(attrs=[190, 191, 226, 167, 470, 5, 8, 315, 472, 399, 514, 339]),
 AttrsSubset(attrs=[167, 6, 392, 269, 190, 15, 4, 317, 207, 488, 339]),
 AttrsSubset(attrs=[132, 15, 167, 11, 190, 209, 312, 4, 8, 495, 6, 338, 30]),
 AttrsSubset(attrs=[123, 15, 680, 8, 737, 510, 6, 5, 294, 315, 335, 466]),
 AttrsSubset(attrs=[189, 8, 659, 169, 6, 404, 140, 597, 491, 124, 510, 341, 4]),
 AttrsSubset(attrs=[123, 351, 124, 8, 4, 7, 404, 489, 6, 516, 597, 335]),
 AttrsSubset(attrs=[0, 11, 167, 6, 389, 728, 190, 207, 517, 340, 491, 5]),
 AttrsSubset(attrs=[6, 389, 190, 296, 464, 189, 490, 336, 4, 735, 313]),
 AttrsSubset(attrs=[123, 190, 6, 716, 208, 5, 515, 489, 318, 471, 337]),
 AttrsSubset(attrs=[190, 191, 6, 392, 5, 123, 142, 318, 207, 515, 603, 4]),
 AttrsSubset(attrs=[123, 15, 6, 386, 124, 5, 406, 313, 339, 294, 4, 318]),
 AttrsSubset(attrs=[25, 15, 11, 416, 656, 675, 412, 141, 8, 6, 317, 335, 492]),
 AttrsSubset(attrs=[201, 15, 168, 413, 473, 412, 468, 515, 8, 489, 6, 728, 340]),
 AttrsSubset(attrs=[6, 392, 291, 142, 407, 729, 189, 4, 516, 312, 515])]

# Show stats for computed reducts

Let us present some statistics of the computed sets of reducts, e.g,. avg, min, max lenght of computed reducts, or the most frequently used columns/attributes.

In [10]:
def stats(reds, name, top, for_objs=False):
    attr_counts = defaultdict(int)
    attrs_lengths = []
    objs_lengths = []

    for elem in reds:
        attrs_lengths.append(len(elem.attrs))
        if for_objs:
            objs_lengths.append(len(elem.objs))
        for a in elem.attrs:
            attr_counts[a] += 1

    attr_counts_df = pd.DataFrame(attr_counts.items(), columns=["attr", "count"])
    attr_counts_df = attr_counts_df.set_index("attr")

    print(f"no of {name}s        = {len(reds)}")
    print(f"avg {name} length    = {np.mean(attrs_lengths)}")
    print(f"median {name} length = {np.median(attrs_lengths)}")
    print(f"min {name} length    = {np.min(attrs_lengths)}")
    print(f"max {name} length    = {np.max(attrs_lengths)}")
    if for_objs:
        print(f"avg {name} objs    = {np.mean(objs_lengths)}")
        print(f"median {name} objs = {np.median(objs_lengths)}")
        print(f"min {name} objs    = {np.min(objs_lengths)}")
        print(f"max {name} objs    = {np.max(objs_lengths)}")
    print("most commonly used attrs (attrs positions starting from 0):")
    print(attr_counts_df.sort_values("count", ascending=False)[:top])


def stats_reducts(reducts, top=10):
    stats(reducts, name="reduct", top=top, for_objs=False)

In [ ]:
stats_reducts(greedy_heuristic_reducts)

no of reducts        = 100
avg reduct length    = 16.38
median reduct length = 16.0
min reduct length    = 15
max reduct length    = 18
most commonly used attrs (attrs positions starting from 0):
      count
attr
6        93
4        63
5        51
123      39
124      32
512      30
189      28
190      27
8        26
492      26

In [ ]:
stats_reducts(daar_heuristic_reducts)

no of reducts        = 100
avg reduct length    = 11.89
median reduct length = 12.0
min reduct length    = 10
max reduct length    = 14
most commonly used attrs (attrs positions starting from 0):
      count
attr
6        83
8        55
4        52
5        42
190      32
189      31
123      31
15       29
168      28
167      24

# Performance of classifiers

The dataset is imbalanced - there is a lot more entities with the one decision than other. So, for performance we will be mainly interested in BAC (Balanced Accuracy) but for reference we also present ACC (Accuracy).

In [ ]:
# see the distribution of the target attribute
pd.Series(target).value_counts()

0    130188
1      2963
Name: count, dtype: int64

In [14]:
# helper functions to present performance measures


def print_perf_values(bac, acc):
    print(f"BAC: {bac}")
    print(f"ACC: {acc}")


def performance_cl(cl):
    """Print performance for a sklearn-compatible classifier."""
    print_perf_values(
        bac=balanced_accuracy_score(test_target, cl.predict(test)),
        acc=accuracy_score(test_target, cl.predict(test)),
    )


def performance_reducts(reducts):
    """Print performance for a set of reducts - they are used as an ensemle of rule-based classifiers."""
    predictions = predict_attrs_ensemble(
        model_ensemble=reducts,
        reference_data=train,
        reference_data_y=train_target,
        predict_data=test,
        fill_missing=0,
    )
    print_perf_values(
        bac=balanced_accuracy_score(test_target, predictions),
        acc=accuracy_score(test_target, predictions),
    )


def performance_bireducts(bireducts):
    """Print performance for a set of bireducts - they are used as an ensemle of rule-based classifiers."""
    predictions = predict_objs_attrs_ensemble(
        model_ensemble=bireducts,
        reference_data=train,
        reference_data_y=train_target,
        predict_data=test,
        fill_missing=0,
    )
    print_perf_values(
        bac=balanced_accuracy_score(test_target, predictions),
        acc=accuracy_score(test_target, predictions),
    )

In [15]:
# performance for Decition Tree Classifier (default settings)

cl = DecisionTreeClassifier()
cl.fit(train, train_target)
performance_cl(cl)

BAC: 0.8338824501595168
ACC: 0.9851306698708321

In [16]:
# performance for Random Forest Classifier (100 estimators + default settings)

cl = RandomForestClassifier(n_estimators=100)
cl.fit(train, train_target)
performance_cl(cl)

BAC: 0.7613405313029951
ACC: 0.9879092820666867

In [17]:
# performance for XGBoost (100 estimators + default settings)

cl = XGBClassifier(n_estimators=100, objective="binary:logistic")
cl.fit(train, train_target)
performance_cl(cl)

BAC: 0.8241538251485261
ACC: 0.9897116251126464

In [18]:
# performance for greedy heuristic reducts

performance_reducts(greedy_heuristic_reducts)

BAC: 0.8440467705997442
ACC: 0.9902373085010514

In [ ]:
# performance for daar heuristic reducts

performance_reducts(daar_heuristic_reducts)

BAC: 0.7270539101907457
ACC: 0.985806548513067

# feature selection

As we could see above, the performance computed for reducts and bireduct (used as rule-based classifiers) is lower than for, e.g., Decision Tree or XGBoost. In some cases they can perform well, but quite often such simple rule-based classifiers are just worse than other more advanced methods. 

The main strength of reducts and bireducts may not be in using them directly as classifiers (as seen above) but as a feature selection method that can help more advanced classifiers perform even better.

In [20]:
def get_attrs_union(reducts):
    """Get union of attribute numbers that are used in the given ``reducts``."""
    return list(functools.reduce(lambda s, red: s | set(red.attrs), reducts, set()))


# e.g., attr numbers used in reducts[0] and reducts[1]
print(get_attrs_union(greedy_heuristic_reducts[:2]))

# e.g., attr numbers used in reducts[1], reducts[2], reducts[3], reducts[4]
print(get_attrs_union(greedy_heuristic_reducts[1:5]))

[0, 516, 5, 6, 4, 8, 201, 517, 75, 203, 334, 15, 207, 400, 338, 471, 601, 538, 603, 605, 121, 294, 167, 493, 494, 54, 312, 313, 123, 316, 125, 190]
[0, 512, 386, 3, 4, 517, 6, 516, 5, 8, 514, 653, 142, 15, 400, 401, 407, 537, 168, 54, 55, 312, 185, 313, 316, 317, 190, 189, 74, 203, 334, 335, 593, 338, 341, 597, 471, 605, 98, 229, 489, 490, 491, 493, 494, 121, 123, 125, 510]

In [ ]:
def get_attrs_merged_in_n(reducts, n: int):
    """Utilize all provided ``reducts`` to randomly shuffle and pair them into tuples
    (pairs, triplets, quintets, etc., depending on ``n``), then combine the attr numbers
    within the resulting tuples.

    When the given number of reducts cannot be split evenly into sets that have exactly ``n`` elements
    then some of them will be smaller.
    """
    shuffled = rng.choice(reducts, size=len(reducts), replace=False)
    return list(map(get_attrs_union, more_itertools.chunked_even(shuffled, n=n)))


# e.g., attrs used in all reducts
attrs_all = get_attrs_union(greedy_heuristic_reducts)

# e.g., randomly shuffle and pair reducts in triplets, join attr numbers within triplets
attrs_in_triplets = get_attrs_merged_in_n(greedy_heuristic_reducts, n=3)

# e.g., randomly shuffle and pair reducts in quintets, join attr numbers within quintets
attrs_in_quintets = get_attrs_merged_in_n(greedy_heuristic_reducts, n=5)

In [ ]:
# Let's prepare an sklearn Pipeline that use only attrs (attrs_all) used in reducts.
# Then, fit the classifier and print its performance.

cl = Pipeline(
    [
        (
            "feature_selection",
            make_column_transformer(("passthrough", attrs_all)),
        ),
        ("cl", DecisionTreeClassifier()),
    ]
)

cl.fit(train, train_target)

performance_cl(cl)

BAC: 0.8225077852113272
ACC: 0.9835536197056173

In [23]:
# A more complex example. Let's prepare an ensemble of Decision Tree Classifiers.
# Each component of the ensemble will use a subset of attr numbers that were used in a given triplet of reducts.

cl = VotingClassifier(
    [
        (
            f"cl{i}",
            Pipeline(
                [
                    (
                        "feature_selection",
                        make_column_transformer(("passthrough", attrs)),
                    ),
                    ("cl", DecisionTreeClassifier()),
                ]
            ),
        )
        for i, attrs in enumerate(attrs_in_triplets)
    ]
)
cl.fit(train, train_target)

performance_cl(cl)

BAC: 0.8582865172220622
ACC: 0.9915139681586062

# feature importance

Moreover, we can use functions from the library to assess attributes. Currently, the interface is not yet in its final shape, i.e., it is still a little bit low-level - there is need to prepare inputs used in the below functions (cf., ``prepare_factorized_array``, ``prepare_factorized_vector``). In future these operations will be hidden inside the functions.

In [30]:
x, x_counts = prepare_factorized_array(train)
y, y_count = prepare_factorized_vector(train_target)
feat_importance_greedy_heuristic = get_feature_importance(
    x=x,
    x_counts=x_counts,
    y=y,
    y_count=y_count,
    column_names=column_names,
    attrs_subsets=greedy_heuristic_reducts,
    disorder_fun=gini_impurity,
)

In [31]:
feat_importance_greedy_heuristic

                                  column  count  global_gain  avg_global_gain
0                     total_bumps_energy    1.0     0.000324         0.000324
1                   total_tremors_energy    0.0     0.000000         0.000000
2        total_destressing_blasts_energy    0.0     0.000000         0.000000
3                   total_seismic_energy    2.0     0.000666         0.000333
4           latest_progress_estimation_l   63.0     0.081092         0.001287
..                                   ...    ...          ...              ...
733  max8_avg_difference_in_gactivity_W2    0.0     0.000000         0.000000
734  max8_avg_difference_in_gactivity_W3    2.0     0.001622         0.000811
735    max8_avg_difference_in_genergy_W1    2.0     0.002007         0.001003
736    max8_avg_difference_in_genergy_W2    9.0     0.009899         0.001100
737    max8_avg_difference_in_genergy_W3    2.0     0.002069         0.001034

[738 rows x 4 columns]

In [32]:
# Let's sort the attributes according to the "count" column - these particular
# ordering should match the order we already have seen above in "Show stats for computed reducts and bireducts"
feat_importance_greedy_heuristic.sort_values("count", ascending=False)[
    ["column", "count", "global_gain"]
].iloc[:10]

                                         column  count  global_gain
6                     latest_seismic_assessment   93.0     0.317649
4                  latest_progress_estimation_l   63.0     0.081092
5                  latest_progress_estimation_r   51.0     0.058277
123                              max24_count_e3   39.0     0.041546
124                              max24_count_e4   32.0     0.029762
512                whichminDiff24_avg_gactivity   30.0     0.034276
189                       maxminDiff24_count_e3   28.0     0.030646
190                       maxminDiff24_count_e4   27.0     0.025482
8               latest_comprehensive_assessment   26.0     0.021823
492  whichmaxDiff24_max_difference_in_gactivity   26.0     0.029856

In [33]:
# Let's see the attribute ordering when "global_gain" feature importance measure is used
feat_importance_greedy_heuristic.sort_values("global_gain", ascending=False)[
    ["column", "count", "global_gain"]
].iloc[:10]

                                         column  count  global_gain
6                     latest_seismic_assessment   93.0     0.317649
4                  latest_progress_estimation_l   63.0     0.081092
5                  latest_progress_estimation_r   51.0     0.058277
123                              max24_count_e3   39.0     0.041546
512                whichminDiff24_avg_gactivity   30.0     0.034276
189                       maxminDiff24_count_e3   28.0     0.030646
492  whichmaxDiff24_max_difference_in_gactivity   26.0     0.029856
124                              max24_count_e4   32.0     0.029762
334                    whichmin24_max_gactivity   24.0     0.029226
121     lastminDiff24_avg_difference_in_genergy   24.0     0.027475

In [35]:
# Let's just use the attribute ranking to select small number of "most important" attributes
# with respect to the "count" measure. Get 30 best attrs and check Decision Tree Classifier
# performance on them.

best_cols = feat_importance_greedy_heuristic.sort_values(
    "count", ascending=False
).index[:30]

cl = Pipeline(
    [
        (
            "feature_selection",
            make_column_transformer(("passthrough", best_cols)),
        ),
        ("cl", DecisionTreeClassifier()),
    ]
)

cl.fit(train, train_target)

performance_cl(cl)

BAC: 0.8418619790270494
ACC: 0.9830279363172124